name: Run SMA Strategy Bot

on:
  schedule:
    - cron: "30 3 * * *"  # Runs daily at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run SMA strategy bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py
